// <auto-generated />
namespace TaskTracker.Repository.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DBSchemaV0_Existing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBSchemaV0_Existing));
        
        string IMigrationMetadata.Id
        {
            get { return "201709220447566_DBSchemaV0_Existing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
