//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [Serializable]
    [DataContract(IsReference = true)]
    public partial class Activity
    {
        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public System.DateTime StartTime { get; set; }

        [DataMember]
        public Nullable<System.DateTime> EndTime { get; set; }

        [DataMember]
        public string Description { get; set; }

        [DataMember]
        public virtual Task Task { get; set; }

        [DataMember]
        public virtual User User { get; set; }
    }
}
