//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker.Model
{
    using System;
    
    public enum Status : byte
    {
        Open = 0,
        InProgress = 1,
        Closed = 2
    }
}
