//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    using TaskTracker.Model;
    
    
    public partial class TaskTrackerModelContainer : DbContext
    {
        public TaskTrackerModelContainer()
            : base("name=TaskTrackerModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Task> TaskSet { get; set; }
        public virtual DbSet<Activity> ActivitySet { get; set; }
        public virtual DbSet<Project> ProjectSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<TaskType> TaskTypeSet { get; set; }
    }
}
